// duilian
export const DUILIAN_SET_GEN_METHOD = 'DUILIAN_SET_GEN_METHOD'
export const DUILIAN_SET_TEXT_INPUT = 'DUILIAN_SET_TEXT_INPUT'
export const DUILIAN_SET_PHOTO_FILE = 'DUILIAN_SET_PHOTO_FILE'

// poem
export const POEM_SET_GEN_METHOD = 'POEM_SET_GEN_METHOD'
export const POEM_SET_TEXT_INPUT = 'POEM_SET_TEXT_INPUT'
export const POEM_SET_PHOTO_FILE = 'POEM_SET_PHOTO_FILE'
export const POEM_SET_IS_CANGTOU = 'POEM_SET_IS_CANGTOU'
export const POEM_SET_NUM_WORDS = 'POEM_SET_NUM_WORDS'

// guwen
export const GUWEN_SET_GEN_METHOD = 'GUWEN_SET_GEN_METHOD'
export const GUWEN_SET_TEXT_INPUT = 'GUWEN_SET_TEXT_INPUT'
export const GUWEN_SET_PHOTO_FILE = 'GUWEN_SET_PHOTO_FILE'
